'use client'

import { useEffect, useMemo, useState } from 'react'
import { authedFetch } from '@/app/lib/authedFetch'

type RequestStatus = 'received' | 'in_review' | 'verified' | 'completed' | 'declined'
type PrivacyRequest = { id: string; action: string; status: RequestStatus; details: string | null; email: string; phone: string; owner_note: string | null; created_at: string }
const labels: Record<string, string> = { access: 'Data copy', correct: 'Correction', delete: 'Deletion review', withdraw_marketing: 'Stop marketing' }

export default function PrivacyRequestsPage() {
  const [items, setItems] = useState<PrivacyRequest[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [filter, setFilter] = useState<'all' | RequestStatus>('all')
  const load = async () => { setLoading(true); setError(''); try { const response = await authedFetch('/api/admin/privacy-requests'); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load privacy requests.'); setItems(data.requests || []) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load privacy requests.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const shown = useMemo(() => filter === 'all' ? items : items.filter(item => item.status === filter), [items, filter])
  const update = async (item: PrivacyRequest, status: RequestStatus, note = item.owner_note || '') => { const response = await authedFetch('/api/admin/privacy-requests', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: item.id, status, owner_note: note }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(data.error || 'Unable to update this request.'); return } setItems(current => current.map(row => row.id === item.id ? { ...row, status, owner_note: note || null } : row)) }
  return <main style={styles.page}><header style={styles.header}><div><p style={styles.eyebrow}>Privacy operations</p><h1 style={styles.title}>Customer data requests</h1><p style={styles.subtitle}>Verify the requester before changing records. Complete a deletion only after confirming any legal, tax, fraud or order-retention requirement.</p></div><button onClick={load} style={styles.refresh}>Refresh</button></header><div style={styles.notice}><strong>Safe handling:</strong> do not paste customer data into chat or email. Record the verification and outcome in the request note.</div><div style={styles.filters}>{(['all', 'received', 'in_review', 'verified', 'completed', 'declined'] as const).map(value => <button key={value} onClick={() => setFilter(value)} style={{ ...styles.filter, ...(filter === value ? styles.active : {}) }}>{value === 'all' ? `All (${items.length})` : value.replace('_', ' ')}</button>)}</div>{error && <p style={styles.error}>{error}</p>}{loading ? <p style={styles.empty}>Loading requests…</p> : shown.length === 0 ? <p style={styles.empty}>No {filter === 'all' ? '' : filter.replace('_', ' ')} requests.</p> : <div style={styles.list}>{shown.map(item => <article key={item.id} style={styles.card}><div style={styles.cardTop}><div><p style={styles.meta}>{new Date(item.created_at).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</p><h2 style={styles.requestType}>{labels[item.action] || item.action}</h2><p style={styles.pii}>{item.email} · {item.phone}</p></div><select value={item.status} onChange={event => update(item, event.target.value as RequestStatus)} style={styles.select} aria-label={`Status for ${labels[item.action] || item.action}`}><option value="received">Received</option><option value="in_review">In review</option><option value="verified">Verified</option><option value="completed">Completed</option><option value="declined">Declined</option></select></div>{item.details && <p style={styles.details}>{item.details}</p>}<label style={styles.noteLabel}>Internal verification / outcome note<textarea value={item.owner_note || ''} onChange={event => setItems(current => current.map(row => row.id === item.id ? { ...row, owner_note: event.target.value } : row))} onBlur={() => update(item, item.status)} rows={3} style={styles.note} placeholder="Example: verified by registered phone on 14 Sep; invoice retention applies until…" /></label></article>)}</div>}</main>
}

const styles: Record<string, React.CSSProperties> = { page: { maxWidth: 1080, margin: '0 auto', padding: '34px 26px 60px', color: '#1a1008' }, header: { display: 'flex', justifyContent: 'space-between', alignItems: 'start', gap: 24, marginBottom: 18 }, eyebrow: { margin: 0, color: '#b7791f', fontWeight: 800, fontSize: 11, letterSpacing: '.14em', textTransform: 'uppercase' }, title: { margin: '6px 0', fontSize: 32, lineHeight: 1.1 }, subtitle: { maxWidth: 680, margin: 0, color: '#6b6258', lineHeight: 1.5 }, refresh: { background: '#1a1008', color: '#fff', border: 0, borderRadius: 5, padding: '10px 16px', fontWeight: 700, cursor: 'pointer' }, notice: { marginBottom: 16, padding: '13px 15px', background: '#fff3d6', border: '1px solid #e3c06a', color: '#5f4310', lineHeight: 1.5, fontSize: 13 }, filters: { display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 18 }, filter: { padding: '7px 10px', border: '1px solid #d9cfbe', background: '#fff', color: '#544b40', cursor: 'pointer', fontWeight: 700, borderRadius: 4, textTransform: 'capitalize' }, active: { background: '#e8c76d', borderColor: '#c8973a', color: '#1a1008' }, error: { padding: 14, background: '#fde7e5', border: '1px solid #e68d82', color: '#8a2419' }, empty: { padding: 36, textAlign: 'center', background: '#fff', border: '1px solid #e8dfd1', color: '#6b6258' }, list: { display: 'grid', gap: 14 }, card: { background: '#fff', border: '1px solid #e8dfd1', padding: 20 }, cardTop: { display: 'flex', justifyContent: 'space-between', gap: 18, alignItems: 'start' }, meta: { margin: 0, color: '#8a7f73', fontSize: 12 }, requestType: { margin: '5px 0 4px', fontSize: 20 }, pii: { margin: 0, color: '#176a5a', fontWeight: 700 }, details: { padding: '10px 12px', background: '#faf6ef', borderLeft: '3px solid #d2aa56', whiteSpace: 'pre-wrap', color: '#413a32' }, select: { padding: '8px 10px', fontWeight: 800, borderRadius: 4, border: '1px solid #d9cfbe', cursor: 'pointer', textTransform: 'capitalize' }, noteLabel: { display: 'block', marginTop: 14, color: '#6b6258', fontSize: 12, fontWeight: 800 }, note: { display: 'block', width: '100%', boxSizing: 'border-box', marginTop: 6, padding: 10, border: '1px solid #d9cfbe', font: 'inherit', color: '#413a32', resize: 'vertical' } }
