'use client'

import { useEffect, useState } from 'react'
import { authedFetch } from '@/app/lib/authedFetch'

type Review = { id: string; product_name?: string; customer_name?: string; rating?: number; review?: string; photo_url?: string; photo_path?: string; created_at?: string }
type Campaign = { eligible_orders: number; recipients: number; preview?: { subject?: string } }

export default function ReviewsPage() {
  const [reviews, setReviews] = useState<Review[]>([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState<string | null>(null), [message, setMessage] = useState('')
  const [campaign, setCampaign] = useState<Campaign | null>(null), [campaignLoading, setCampaignLoading] = useState(true), [sending, setSending] = useState(false)
  async function loadCampaign() { setCampaignLoading(true); try { const response = await authedFetch('/api/admin/review-request-campaign'); const data = await response.json(); setCampaign(response.ok ? data : null) } finally { setCampaignLoading(false) } }
  async function load() { setLoading(true); try { const response = await authedFetch('/api/admin/reviews?status=pending'); const data = await response.json(); setReviews(response.ok && Array.isArray(data.reviews) ? data.reviews : []) } finally { setLoading(false) }; await loadCampaign() }
  useEffect(() => { load() }, [])
  async function moderate(id: string, action: 'approve' | 'reject') { setBusy(id); setMessage(''); try { const response = await authedFetch('/api/admin/reviews', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, action }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error || 'Unable to update the review.'); return } setReviews(current => current.filter(review => review.id !== id)); setMessage(action === 'approve' ? (data.alreadyAwarded ? 'Review published. Its reward was already recorded.' : `Review published and ${data.pointsAwarded} points awarded.`) : 'Review rejected.') } finally { setBusy(null) } }
  async function sendCampaign() { if (!campaign?.recipients || !window.confirm(`Send the review invitation email to ${campaign.recipients} eligible customers now?`)) return; setSending(true); setMessage(''); try { const response = await authedFetch('/api/admin/review-request-campaign', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirm: true }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error || 'Unable to send review invitations.'); return }; setMessage(`Review invitations sent to ${data.emails_sent} customers${data.failed ? `; ${data.failed} could not be sent.` : '.'}`); await loadCampaign() } finally { setSending(false) } }
  return <div style={{ maxWidth: 1080, margin: '0 auto', padding: 28 }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'end', marginBottom: 24 }}><div><h1 style={{ margin: 0, color: '#1a1008', fontSize: 29 }}>Review approval</h1><p style={{ color: '#6b7280', margin: '7px 0 0', fontSize: 14 }}>Published reviews appear on the matching product page. Approve a text review for 100 points, or one with a dog photo for 150 points.</p></div><button onClick={load} style={{ border: '1px solid #d6c9b8', background: '#fff', padding: '9px 14px', cursor: 'pointer', borderRadius: 5, fontWeight: 700 }}>Refresh</button></div>
    {message && <div style={{ marginBottom: 16, padding: 12, background: '#ecfdf5', color: '#166534', border: '1px solid #bbf7d0', borderRadius: 6 }}>{message}</div>}
    <section style={{ background: '#fff9ec', border: '1px solid #e4c988', borderRadius: 8, padding: 20, marginBottom: 22 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, flexWrap: 'wrap' }}><div><h2 style={{ color: '#1a1008', margin: 0, fontSize: 19 }}>Review invitation campaign</h2><p style={{ color: '#64584a', margin: '7px 0 0', fontSize: 14 }}>{campaignLoading ? 'Checking eligible delivered orders…' : campaign ? `${campaign.recipients} customers across ${campaign.eligible_orders} delivered paid orders will receive “${campaign.preview?.subject || 'Tell us how treat time went'}”. Free orders and products already reviewed are excluded.` : 'Campaign preview is unavailable. Refresh to retry.'}</p><p style={{ color: '#64584a', margin: '7px 0 0', fontSize: 13 }}>The email invites customers to review only products they bought and explains the 100-point text / 150-point dog-photo reward.</p></div><button disabled={campaignLoading || !campaign?.recipients || sending} onClick={sendCampaign} style={{ border: 0, background: campaign?.recipients ? '#1f6b4d' : '#9ca3af', color: '#fff', padding: '11px 16px', cursor: campaign?.recipients ? 'pointer' : 'not-allowed', borderRadius: 5, fontWeight: 700, whiteSpace: 'nowrap' }}>{sending ? 'Sending…' : `Send ${campaign?.recipients || 0} invitations`}</button></div></section>
    {loading ? <div style={{ color: '#6b7280', padding: 30 }}>Loading reviews…</div> : reviews.length === 0 ? <div style={{ background: '#fff', border: '1px solid #e7ded0', borderRadius: 8, padding: 32, color: '#6b7280', textAlign: 'center' }}>No pending reviews.</div> : <div style={{ display: 'grid', gap: 14 }}>{reviews.map(review => <article key={review.id} style={{ background: '#fff', border: '1px solid #e7ded0', borderRadius: 8, padding: 20 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 16 }}><div><strong style={{ color: '#1a1008' }}>{review.customer_name || 'Customer'}</strong><div style={{ color: '#c88722', marginTop: 5 }}>{'★'.repeat(Math.max(0, Math.min(5, Number(review.rating) || 0)))}</div><small style={{ color: '#6b7280' }}>{review.product_name || 'Product'}</small></div><div style={{ color: '#6b7280', fontSize: 12 }}>{review.created_at ? new Date(review.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : ''}</div></div><p style={{ color: '#374151', lineHeight: 1.55, margin: '14px 0' }}>{review.review || 'No review text supplied.'}</p>{review.photo_url && <img src={review.photo_url} alt="Customer's dog enjoying the treat" style={{ display: 'block', width: 160, height: 120, objectFit: 'cover', borderRadius: 6, marginBottom: 15 }} />}<div style={{ display: 'flex', gap: 9 }}><button disabled={busy === review.id} onClick={() => moderate(review.id, 'approve')} style={{ border: 0, background: '#1f6b4d', color: '#fff', padding: '10px 15px', cursor: 'pointer', borderRadius: 5, fontWeight: 700 }}>{busy === review.id ? 'Saving…' : `Publish + ${review.photo_path ? '150' : '100'} points`}</button><button disabled={busy === review.id} onClick={() => moderate(review.id, 'reject')} style={{ border: '1px solid #d6c9b8', background: '#fff', color: '#5f3219', padding: '10px 15px', cursor: 'pointer', borderRadius: 5, fontWeight: 700 }}>Reject</button></div></article>)}</div>}
  </div>
}
